name: Deploy Redis to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to EC2 and deploy Redis
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull redis:7.2
            sudo docker stop redis-server || true
            sudo docker rm redis-server || true
            sudo docker run -d --name redis-server -p 6379:6379 redis:7.2
